spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ecommerce_user_service
    name: ecommerce_user_service
    username: test
    password: password
    pool:
      initial-size: 5
      max-size: 25
      max-idle-time: 10m
      max-create-connection-time: 2m
  jackson:
    time-zone: Asia/Dhaka
  data:
    r2dbc:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_authentication_service
      database: ecommerce_authentication_service
      repositories:
        type: reactive
server:
  port: 8090
  forward-headers-strategy: framework
  netty:
    connection-timeout: 2m
    idle-timeout: 15m
  error:
    include-message: always
    include-exception: false
    include-binding-errors: always
    include-stacktrace: never
  shutdown: graceful