spring:
  r2dbc:
    url: r2dbc:h2:mem://testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      database: test
  mongodb:
    embedded:
      version: 4.0.21