spring:
  application:
    name: auth-service
  profiles:
    default: dev
    active: dev
  webflux:
    base-path: /auth-api
info:
  application:
    metadata:
      name: ${spring.application.name}
      description: Authentication Service for spring-microservices-demo
      version: 1.0.0-SNAPSHOT
    developer:
      name: Syed Riadh Hossen
      email: hossensyedriadh@gmail.com
      url: https://hossensyedriadh.github.io
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
bearer-authentication:
  keystore:
    location: ${keystore_location}
    passphrase: ${keystore_passphrase}
    private-key-passphrase: ${keystore_private_passphrase}
    key-alias: authentication
  tokens:
    access-token:
      type: Bearer
      validity-mins: 60
    refresh-token:
      validity-mins: 360
