server:
  forward-headers-strategy: framework
  netty:
    connection-timeout: 2m
    idle-timeout: 15m
  error:
    include-message: always
    include-exception: false
    include-binding-errors: always
    include-stacktrace: never
  shutdown: immediate
management:
  endpoints:
    web:
      exposure:
        include: info,health
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
