spring:
  application:
    name: edge-service
  profiles:
    default: dev
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products-api/**
          filters:
            - BearerAuthenticationFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders-api/**
          filters:
            - BearerAuthenticationFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users-api/**
          filters:
            - BearerAuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-api/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
bearer-authentication:
  public-key:
    path: ${bearer_auth_certificate}
  tokens:
    access-token:
      type: Bearer
management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,gateway
      cors:
        max-age: 3600s
        allowed-origins: "*"
        allowed-headers: "*"
        allowed-methods: "*"
        allow-credentials: false
info:
  application:
    metadata:
      name: ${spring.application.name}
      description: Edge Service for spring-microservices-demo
      version: 1.0.0-SNAPSHOT
    developer:
      name: Syed Riadh Hossen
      email: hossensyedriadh@gmail.com
      uri: https://hossensyedriadh.github.io
server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-stacktrace: never
    include-exception: true
    include-binding-errors: always
