spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ecommerce_user_service
    name: ecommerce_user_service
    username: test
    password: password
    pool:
      initial-size: 3
      max-size: 20
      max-idle-time: 10m
      max-create-connection-time: 2m
  jackson:
    time-zone: Asia/Dhaka
  data:
    r2dbc:
      repositories:
        enabled: true
server:
  port: 9000
  forward-headers-strategy: framework
  netty:
    connection-timeout: 2m
    idle-timeout: 15m
  error:
    include-message: always
    include-exception: false
    include-binding-errors: always
    include-stacktrace: never