spring:
  application:
    name: order-service
  profiles:
    default: dev
    active: dev
  webflux:
    base-path: /orders-api
  data:
    rest:
      default-page-size: 14
      max-page-size: 34
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
    fetch-registry: true
    register-with-eureka: true
info:
  application:
    metadata:
      name:
        ${spring.application.name}
      description: Order Service for spring-microservices-demo
      version: 1.0.0-SNAPSHOT
    developer:
      name: Syed Riadh Hossen
      email: hossensyedriadh@gmail.com
      url: https://hossensyedriadh.github.io
kafka:
  producer:
    topic:
      create-order: CREATE-ORDER-TOPIC
      update-order: UPDATE-ORDER-TOPIC
