spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_order_service
      database: ecommerce_order_service
      username: test
      password: password
      repositories:
        type: reactive
  jackson:
    time-zone: Asia/Dhaka
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  forward-headers-strategy: framework
  netty:
    connection-timeout: 2m
    idle-timeout: 15m
  error:
    include-message: always
    include-exception: false
    include-binding-errors: always
    include-stacktrace: never
management:
  endpoints:
    web:
      exposure:
        include: info,health
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
