spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_product_service
      database: ecommerce_product_service
      username: test
      password: password
      repositories:
        type: reactive
server:
  forward-headers-strategy: framework
  netty:
    connection-timeout: 2m
    idle-timeout: 15m
  error:
    include-message: always
    include-exception: false
    include-binding-errors: always
    include-stacktrace: never
  shutdown: immediate
management:
  endpoints:
    web:
      exposure:
        include: info,health
